/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AppUserRole = { 'client' : null } |
  { 'editor' : null };
export type ExternalBlob = Uint8Array;
export interface Job {
  'status' : JobStatus,
  'completedAt' : [] | [Time],
  'clientId' : Principal,
  'assignedEditorId' : [] | [Principal],
  'createdAt' : Time,
  'jobId' : string,
  'sourceVideo' : ExternalBlob,
  'finalVideo' : [] | [ExternalBlob],
  'videoType' : VideoType,
  'notes' : string,
  'stripeSessionId' : [] | [string],
  'price' : bigint,
  'referenceVideo' : ExternalBlob,
}
export interface JobInput {
  'sourceVideo' : ExternalBlob,
  'videoType' : VideoType,
  'notes' : string,
  'referenceVideo' : ExternalBlob,
}
export type JobStatus = { 'assigned' : null } |
  { 'pending_payment' : null } |
  { 'pending' : null } |
  { 'in_progress' : null } |
  { 'completed' : null };
export type Principal = Principal;
export interface RevenueSummary {
  'totalRevenue' : bigint,
  'completedJobsCount' : bigint,
  'paidJobsCount' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'appRole' : AppUserRole, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VideoType = { 'long' : null } |
  { 'small' : null } |
  { 'medium' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminSubmitFinalVideo' : ActorMethod<[string, ExternalBlob], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignJob' : ActorMethod<[string, Principal], undefined>,
  'confirmPayment' : ActorMethod<[string, string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'getAllJobs' : ActorMethod<[], Array<Job>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getJob' : ActorMethod<[string], Job>,
  'getRevenueSummary' : ActorMethod<[], RevenueSummary>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAdminPasskey' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitFinalVideo' : ActorMethod<[string, ExternalBlob], undefined>,
  'submitJob' : ActorMethod<[JobInput], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'verifyAdminPasskey' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];